src/main/java/controller/AdminPageController.java
package controller;

import javax.faces.bean.*;
import javax.faces.context.FacesContext;

import dao.PersonDao;
import org.springframework.stereotype.Component;
import service.PersonService;

/**
 * Created by varianytsia on 09.12.17.
 */
@Component
@ManagedBean(name = "adminPageController",eager = true)
@RequestScoped
public class AdminPageController{

@ManagedProperty(value = "#{personService}")
  PersonService personService;

public String getUserName(){
String userLogin = FacesContext.getCurrentInstance().getExternalContext().getRemoteUser();
return personService.getPersonByLogin(userLogin).getFirstName();
}

public String navigateToOrderList(){
    return "/pages/orderListPage?faces-redirect=true";
}

public PersonService getPersonService() {
        return personService;
    }

    public void setPersonService(PersonService personService) {
        this.personService = personService;
    }
}

src/main/webapp/pages/addOrderPage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>Add order</title>
</h:head>

<h:body>
<ui:composition template="../templates/layout.xhtml">

    <ui:define name="content">
        <ui:param name="ctrl" value="#{orderListController}" />
        <ui:param name="updateCtrl" value="#{updateOrderController}" />
        <h2 align="center" class="page_title">Add new order</h2>

        <h:form id="addForm">
            <p:growl id="message"/>
        <h:panelGrid columns="7">


            <h:column>
             <h:panelGrid>
                <f:facet name="header">Car</f:facet>
                 <h:selectOneMenu id="car_select" value="#{ctrl.targetOrder.car.carId}" required="true" requiredMessage="Please select a car">
                     <f:selectItem itemLabel=""/>
                    <f:selectItems value="#{ctrl.cars}" var="car" itemValue="#{car.carId}" itemLabel="#{car.carNumber}"/>
                </h:selectOneMenu>
             </h:panelGrid>
             </h:column>

            <h:column>
            <h:panelGrid>
                <f:facet name="header">Client</f:facet>
                <h:selectOneMenu value="#{ctrl.targetOrder.clientId}">
                    <f:selectItem itemLabel=""/>
                    <f:selectItems value="#{ctrl.clients}" var="person" itemValue="#{person.personId}" itemLabel="#{person.firstName} #{person.personLastName}"/>
                </h:selectOneMenu>
            </h:panelGrid>
            </h:column>


            <h:column>
            <h:panelGrid>
                <f:facet name="header">Order Status</f:facet>
                <h:selectOneMenu value="#{ctrl.targetOrder.orderStatus.orderStatusId}" required="true" requiredMessage="Please select Order Status">
                    <f:selectItem itemLabel=""/>
                    <f:selectItems value="#{ctrl.orderStatusList}" var="status" itemValue="#{status.orderStatusId}" itemLabel="#{status.orderStatus}"/>
                </h:selectOneMenu>
            </h:panelGrid>
            </h:column>


            <h:column>
            <h:panelGrid>
                <f:facet name="header">Repairer</f:facet>
                <h:selectOneMenu value="#{ctrl.targetOrder.repairerId}">
                    <f:selectItem itemLabel=""/>
                    <f:selectItems value="#{ctrl.repairers}" var="person" itemValue="#{person.personId}" itemLabel="#{person.firstName} #{person.personLastName}"/>
                </h:selectOneMenu>
            </h:panelGrid>
            </h:column>

            <h:column>
            <h:panelGrid>
                <f:facet name="header">Order Price</f:facet>
                <h:inputText value="#{ctrl.targetOrder.orderPrice}" size="10" />
            </h:panelGrid>
            </h:column>


            <h:column>
            <h:panelGrid>
                <f:facet name="header">Comments</f:facet>
                <h:inputText label="" value="#{ctrl.targetOrder.lastComment.commentText}" required="true" requiredMessage="Please leave the comment" size="15"/>
            </h:panelGrid>
            </h:column>

            <h:column>
            <h:panelGrid>
            <p:commandButton value="save" action="#{orderListController.confirmAddOrder}" update="addForm:message"/>

            <p:commandButton value="cancel" action="#{updateCtrl.cancelUpdateAction}" immediate = "true" update="addForm:message"/>
            </h:panelGrid>
            </h:column>
        </h:panelGrid>

        </h:form>


    </ui:define>



</ui:composition>

</h:body>
</html>

src/main/webapp/pages/adminpage.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">


<h:head>

</h:head>

<h:body>

    <ui:composition template="../templates/layout.xhtml">
        <ui:define name="content" >
            <ui:param name="ctrl" value="#{adminPageController}" />
            <h1 class="greetings">
            <h:outputLabel styleClass="greetings" value="Welcome : #{ctrl.userName}" />
            </h1>
            <div class="topspace"></div>

            <h:form rendered="#{request.isUserInRole('ROLE_ADMINISTRATOR')}">
            <p:commandButton id="orders" styleClass="button" ajax="false" value="Orders" action="#{ctrl.navigateToOrderList()}" />
            </h:form>

            <h:form rendered="#{request.isUserInRole('ROLE_ADMINISTRATOR') || request.isUserInRole('ROLE_REPAIRER')}">
                <p:commandButton id="repairers" styleClass="button" ajax="false" value="Repairers" action="#{ctrl.navigateToOrderList()}" />
            </h:form>

            <h:form rendered="#{request.isUserInRole('ROLE_ADMINISTRATOR')}">
                <p:commandButton id="users" styleClass="button" ajax="false" value="Users" action="#{ctrl.navigateToOrderList()}" />
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>

</html>

src/main/webapp/pages/orderListPage.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
    <title>Orders</title>
</h:head>

<h:body>

<ui:composition template="../templates/layout.xhtml">

    <ui:define name="content">
        <ui:param name="ctrl" value="#{orderListController}" />
        <ui:param name="addCtrl" value="#{updateOrderController}" />

        <h2 align="center" class="page_title">Orders:</h2>

        <div align="center" style="vertical-align: top">
            <h:form rendered="#{request.isUserInRole('ROLE_ADMINISTRATOR')}">
                <h:commandButton styleClass="home_button" value="add new order" ajax="false" action="#{ctrl.addOrder}"/>
            </h:form>
        </div>
        <h:form id="ordersForm">
            <p:growl id="message"/>
        <h:dataTable id="orders" value="#{ctrl.orderList}" var="o" style="width: 100%">

            <h:column>
                <f:facet name="header">ID</f:facet>
                <h:outputText value="#{o.orderId}" />
            </h:column>

            <h:column>
                <f:facet name="header">Car</f:facet>
                <h:outputText value="#{o.car.carNumber}"/>
            </h:column>

            <h:column>
                <f:facet name="header">Client Name</f:facet>
                <h:outputText value="#{ctrl.getClient(o.clientId).firstName} #{ctrl.getClient(o.clientId).personLastName}"/>
            </h:column>

            <h:column>
                <f:facet name="header">Order Status</f:facet>
                <h:outputText value="#{o.orderStatus.orderStatus}"/>
            </h:column>

            <h:column>
                <f:facet name="header">Repairer Name</f:facet>
                <h:outputText value="#{ctrl.getRepairer(o.repairerId).firstName} #{ctrl.getRepairer(o.repairerId).personLastName}"/>
            </h:column>

            <h:column>
                <f:facet name="header">Order Price</f:facet>
                <h:outputText value="#{o.orderPrice}"/>
            </h:column>

            <h:column>
                <f:facet name="header">Comments</f:facet>
                <h:dataTable id = "comments" value="#{o.commentList}" var="comment" styleClass="align:left;">
                    <h:column>
                        #{comment.person.firstName} #{comment.person.personLastName} : #{comment.commentDateTime} #{comment.commentText}
                    </h:column>
                </h:dataTable>
            </h:column>

            <h:column>
                <f:facet name="header"></f:facet>
                <p:commandButton value="update order" action="#{addCtrl.editAction(o)}"/>
            </h:column>

        </h:dataTable>
    </h:form>
    </ui:define>

</ui:composition>

</h:body>
</html>

src/main/webapp/pages/updateOrderPage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <title>Update order</title>
</h:head>

<h:body>
    <ui:composition template="../templates/layout.xhtml">
        <ui:define name="content">
            <ui:param name="ctrl" value="#{updateOrderController}" />
            <ui:param name="listCtrl" value="#{orderListController}" />

            <h2 align="center" class="page_title">Update order</h2>

            <h:form id="addForm">
                <p:growl id="message"/>
                <h:panelGrid columns="8">

                    <h:column>
                        <h:panelGrid>
                         <f:facet name="header">ID</f:facet>
                           <h:outputText value="#{ctrl.targetOrder.orderId}" />
                        </h:panelGrid>
                    </h:column>

                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Car</f:facet>
                            <h:selectOneMenu id="car_select" value="#{ctrl.targetOrder.car.carId}">
                                <f:selectItem itemLabel="#{ctrl.targetOrder.car.carNumber}" itemValue="#{ctrl.targetOrder.car.carId}"/>
                                <f:selectItems value="#{listCtrl.cars}" var="car" itemValue="#{car.carId}" itemLabel="#{car.carNumber}"/>
                            </h:selectOneMenu>
                        </h:panelGrid>
                    </h:column>

                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Client</f:facet>
                            <h:selectOneMenu value="#{ctrl.targetOrder.clientId}">
                                <f:selectItem itemLabel="#{listCtrl.getClient(ctrl.targetOrder.clientId).firstName} #{listCtrl.getClient(ctrl.targetOrder.clientId).personLastName}" itemValue="#{ctrl.targetOrder.clientId}"/>
                                <f:selectItems value="#{listCtrl.clients}" var="person" itemValue="#{person.personId}" itemLabel="#{person.firstName} #{person.personLastName}"/>
                            </h:selectOneMenu>
                        </h:panelGrid>
                    </h:column>


                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Order Status</f:facet>
                            <h:selectOneMenu value="#{ctrl.targetOrder.orderStatus.orderStatusId}">
                                <f:selectItem itemLabel="#{ctrl.targetOrder.orderStatus.orderStatus}" itemValue="#{ctrl.targetOrder.orderStatus.orderStatusId}"/>
                                <f:selectItems value="#{listCtrl.orderStatusList}" var="status" itemValue="#{status.orderStatusId}" itemLabel="#{status.orderStatus}"/>
                            </h:selectOneMenu>
                        </h:panelGrid>
                    </h:column>


                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Repairer</f:facet>
                            <h:selectOneMenu value="#{ctrl.targetOrder.repairerId}">
                                <f:selectItem itemLabel="#{listCtrl.getRepairer(ctrl.targetOrder.repairerId).firstName} #{listCtrl.getRepairer(ctrl.targetOrder.repairerId).personLastName}" itemValue="#{ctrl.targetOrder.repairerId}"/>
                                <f:selectItems value="#{listCtrl.repairers}" var="person" itemValue="#{person.personId}" itemLabel="#{person.firstName} #{person.personLastName}"/>
                            </h:selectOneMenu>
                        </h:panelGrid>
                    </h:column>

                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Order Price</f:facet>
                            <h:inputText value="#{ctrl.targetOrder.orderPrice}" size="10" />
                        </h:panelGrid>
                    </h:column>


                    <h:column>
                        <h:panelGrid>
                            <f:facet name="header">Comments</f:facet>
                            <h:inputText value="#{ctrl.targetOrder.lastComment.commentText}" required="true" requiredMessage="Please leave the comment" size="10"/>
                        </h:panelGrid>
                    </h:column>
                <h:column>
                <h:panelGrid>
                        <p:commandButton value="save" action="#{ctrl.confirmUpdateOrder}" update="addForm:message"/>

                        <p:commandButton value="cancel" action="#{ctrl.cancelUpdateAction}" immediate = "true" update="addForm:message"/>

                </h:panelGrid>
                </h:column>
                </h:panelGrid>

            </h:form>


        </ui:define>



    </ui:composition>

</h:body>
</html>